services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: api
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - .:/api
    command: "/bin/bash"
    stdin_open: true
    tty: true
    environment:
      PORT: 8000
      DB_URL: "postgresql://postgres:example@db:5432/postgres"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: example

networks:
  default:
    name: localnet
