services:
  configuracion:
    build:
      context: .
      dockerfile: Dockerfile
    image: configuracion
    container_name: configuracion
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: "/bin/bash"
    stdin_open: true
    tty: true