name: CI
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Deploy
        env:
          deploy_url: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl "$deploy_url"
